DROP TABLE IF EXISTS opinion_signals CASCADE;
DROP TABLE IF EXISTS matchups CASCADE;
DROP TABLE IF EXISTS recommendations CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS books CASCADE;

DROP TYPE IF EXISTS review_status CASCADE;
DROP TYPE IF EXISTS review_entry_type CASCADE;
DROP TYPE IF EXISTS opinion_type CASCADE;
DROP TYPE IF EXISTS opinion_response CASCADE;
DROP TYPE IF EXISTS matchup_result_type CASCADE;